version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.8.2
  node: circleci/node@2.0
    version: "12.16.3"

workflows:
  test:
    jobs:
      - node/test

  build_and_push_image:
    jobs:
      - request-build_and_push:
          type: approval
          filters:
            branches:
              only: master

      - aws-ecr/build-and-push-image:
          requires:
            - request-build_and_push
          context: ecr-sample
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_REGION
          repo: "${REPO_NAME}"
          tag: "latest-app"
          dockerfile: "./docker/app/Dockerfile"

      - aws-ecr/build-and-push-image:
          requires:
            - request-build_and_push
          context: ecr-sample
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_REGION
          repo: "${REPO_NAME}"
          tag: "latest-web"
          path: "./docker/web"
