name: build
on:
  pull_request:
    types: [opend, synchronize]
jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run build image
        run: |
          docker build -t BUILD -f docker/app/Dockerfile/ docker/app/