name: build
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run build image
        run: |
          docker build --target production -t build:test -f docker/app/Dockerfile .